[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "solady/=lib/solady/",
    "forge-std/=lib/forge-std/src/"
]
metadata = true
metadata_hash = "none" # disable ipfs
use_literal_content = true # use source code

optimizer = true
optimizer_runs = 1000000

# Monad Configuration
eth-rpc-url = "https://testnet-rpc.monad.xyz"
chain_id = 10143

[rpc_endpoints]
monad_testnet = "https://testnet-rpc.monad.xyz"
